### ISSUE TITLE
H&E images

### ISSUE THREAD

**Issue by JunMa11** [cclab-brca/neoadjuvant-therapy-response-predictor#1]
Thanks for sharing the awesome work.

Could you please share the H&E images in this paper?

**Comment by stephensammut** [comment]
Thank you for getting in touch!

Requests for unprocessed raw data should be directed to our data access committee, which currently can be contacted at the following email address: Marion [dot] Karniely [at] cruk [dot] cam [dot] ac [dot] uk

The data sharing documentation for this study is currently under review with our legal department, and we hope that we will be in a position to share the data sharing agreements with the community soon.

**Comment by JunMa11** [comment]
Hi @stephensammut , 

How is the data-sharing documentation review going? Can the pathology data be publicly available now?
Looking forward to your reply:)

**Comment by stephensammut** [comment]
Hi Jun - the data is publicly available and can be downloaded from:

https://zenodo.org/record/6337925#.Y30d1y-l1Ls

**Comment by JunMa11** [comment]
Thank you so much:)
